config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'
  resources :booking_requests, only: %i[new create show] do
    member do
      get :confirm
      post :sign
      post :renew
    end
  end

  namespace :admin do
    resources :booking_requests, only: :index do
      member do
        post :accept
        post :decline
      end
    end
  end

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  self.implicit_order_column = 'created_at'
end

app/models/booking_request.rb
# frozen_string_literal: true

class BookingRequest < ApplicationRecord
  include AASM

  BIO_MIN_WORDS = 5

  validates :name, presence: true
  validates :email, email: true
  validates :phone, phone: true
  validate :biography_is_good_enough

  after_validation :normalize_phone

  after_commit :send_email_verification, on: :create

  aasm column: 'state', timestamps: true do
    state :unconfirmed, initial: true
    state :confirmed
    state :accepted
    state :contract_signed
    state :expired
    state :declined

    event :confirm do
      transitions from: :unconfirmed, to: :confirmed
    end

    event :accept do
      transitions from: :confirmed, to: :accepted
    end

    event :sign do
      transitions from: :accepted, to: :contract_signed
    end

    event :decline do
      transitions from: :confirmed, to: :declined
    end

    event :expire do
      transitions from: :accepted, to: :expired
    end

    event :renew do
      transitions from: :contract_signed,
        to: :contract_signed,
        after: :touch_renewed_at,
        guard: :will_expire_soon?
    end
  end

  # Redefine confirmed scope to sort by confirmation date
  scope :confirmed, -> { where(state: BookingRequest::STATE_CONFIRMED).order(:confirmed_at) }

  # Group state accepted and contract_signed
  scope :accepted, -> { where(state: [BookingRequest::STATE_ACCEPTED, BookingRequest::STATE_CONTRACT_SIGNED,]).order(:accepted_at) }


  def signature_required?
    accepted? && !contract_signed_at
  end

  def contract_expire_at
    return nil unless contract_signed?

    (renewed_at || accepted_at) + 3.months
  end

  def renewing_period
    beginning = contract_expire_at - 10.days
    beginning..contract_expire_at
  end

  def will_expire_soon?
    return false unless contract_signed?

    renewing_period.cover?(Time.zone.now)
  end

  def will_expire_now?
    return false unless contract_signed?

    contract_expire_at <= Time.zone.now
  end

  def send_email_verification
    BookingRequestMailer.with(booking_request: self, token: 'FOO').email_verification.deliver_later
  end

  private

  def normalize_phone
    self.phone = Phonelib.parse(phone).full_e164.presence
  end

  def biography_is_good_enough
    errors.add(:biography, :invalid) if biography.to_s.split(/\W/).length < BIO_MIN_WORDS
  end

  def touch_renewed_at
    self.renewed_at = Time.zone.now
  end
end

app/controllers/admin/booking_requests_controller.rb
class Admin::BookingRequestsController < ApplicationController
  before_action :set_booking_request, only: %i[accept decline]

  def index
    @confirmed_requests = BookingRequest.confirmed
    @accepted_requests = BookingRequest.accepted
  end

  def accept
    outcome = AcceptBookingRequest.run(booking_request: @booking_request)

    respond_to do |format|
      if outcome.valid?
        format.html { redirect_to admin_booking_requests_path, notice:  I18n.t('booking_request.events.accepted') }
      else
        format.html { redirect_to admin_booking_requests_path, alert: outcome.errors.full_messages.join(', ') }
      end
    end
  end

  def decline
    outcome = DeclineBookingRequest.run(booking_request: @booking_request)

    respond_to do |format|
      if outcome.valid?
        format.html { redirect_to admin_booking_requests_path, notice: I18n.t('booking_request.events.declined') }
      else
        format.html { redirect_to admin_booking_requests_path, alert: outcome.errors.full_messages.join(', ') }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_booking_request
    @booking_request = BookingRequest.find(params[:id])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/booking_requests_controller.rb
# frozen_string_literal: true

class BookingRequestsController < ApplicationController
  before_action :set_booking_request, only: %i[show edit confirm sign renew]

  # GET /booking_requests or /booking_requests.json
  def index
    @booking_requests = BookingRequest.all
  end

  # GET /booking_requests/1 or /booking_requests/1.json
  def show; end

  # GET /booking_requests/new
  def new
    @booking_request = BookingRequest.new
  end

  # GET /booking_requests/1/edit
  def edit; end

  # POST /booking_requests or /booking_requests.json
  def create
    @booking_request = BookingRequest.new(booking_request_params)

    respond_to do |format|
      if @booking_request.save
        format.html do
          redirect_to booking_request_url(@booking_request), notice: I18n.t('booking_request.events.created')
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # POST /booking_requests/1/confirm
  def confirm
    outcome = ConfirmBookingRequest.run(booking_request: @booking_request, token: params[:token])
    respond_to do |format|
      if outcome.valid?
        format.html do
          redirect_to booking_request_url(@booking_request), notice: I18n.t('booking_request.events.confirmed')
        end
      else
        format.html { redirect_to booking_request_url(@booking_request), error: outcome.errors.full_messages }
      end
    end
  end

  # POST /booking_requests/1/sign
  def sign
    outcome = SignContract.run(booking_request: @booking_request)
    respond_to do |format|
      if outcome.valid?
        format.html do
          redirect_to booking_request_url(@booking_request), notice: I18n.t('booking_request.events.signed')
        end
      else
        format.html {  redirect_to booking_request_url(@booking_request), error: outcome.errors.full_messages }
      end
    end
  end

  # POST /booking_requests/1/renew
  def renew
    outcome = RenewContract.run(booking_request: @booking_request)
    respond_to do |format|
      if outcome.valid?
        format.html do
          redirect_to booking_request_url(@booking_request), notice: I18n.t('booking_request.events.renewed')
        end
      else
        format.html {  redirect_to booking_request_url(@booking_request), error: outcome.errors.full_messages }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_booking_request
    @booking_request = BookingRequest.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def booking_request_params
    params.require(:booking_request).permit(:name, :email, :phone, :biography)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/admin/booking_requests_helper.rb
module Admin::BookingRequestsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/booking_requests_helper.rb
# frozen_string_literal: true

module BookingRequestsHelper
  STATE_STYLES = {
    unconfirmed: 'is-warning',
    confirmed: 'is-info',
    accepted: 'is-info',
    contract_signed: 'is-success',
    expired: 'is-danger'
  }.with_indifferent_access.freeze

  def status_label(state)
    I18n.t("booking_request.states.#{state}.label")
  end

  def status_tag(state)
    style = STATE_STYLES[state]
    tag.span status_label(state), class: "tag #{style}"
  end

  def contract_status(date)
    if date
      tag.span "Signé", class: "tag is-info"
    else
      tag.span "Non Signé", class: "tag is-warning"
    end
  end
end

app/views/admin/booking_requests/_booking_request.html.slim
.block
  .card
    .card-content
      .columns
        .column
          strong> Demandé le :
          span = time_tag booking_request.created_at
          br
          strong> Nom :
          span = booking_request.name
          br
          strong> Email :
          span = booking_request.email
          br
          strong> Tél. :
          span = booking_request.phone
        .column
          strong Biographie
          br
          = booking_request.biography
    .card-footer
      -if booking_request.confirmed?
        = link_to 'Accepter', accept_admin_booking_request_path(booking_request), class: 'card-footer-item', data: {turbo_method: :post}
        = link_to 'Refuser', decline_admin_booking_request_path(booking_request), class: 'card-footer-item', data: {turbo_method: :post}

app/views/admin/booking_requests/index.html.slim
h2.title.is-4 Demandes de réservation en attente

-if @confirmed_requests.present?
  = render partial: 'booking_request', collection: @confirmed_requests
- else
  .notification
    | Il y a aucune demande de réservation en attente de validation.

h2.title.is-4 Demandes acceptés

-if @accepted_requests.present?
  = render partial: 'booking_request', collection: @accepted_requests
-else
  .notification
  | Il y a aucune demande de réservation acceptées

app/views/booking_requests/_booking_request.html.slim
div id="#{dom_id booking_request}"
  h2.title.is-4 Votre demande de réservation
  .block
    strong> Demandé le :
    span = time_tag @booking_request.created_at
    br
    strong> Nom :
    span = @booking_request.name
    br
    strong> Email :
    span = @booking_request.email
    br
    strong> Tél. :
    span = @booking_request.phone
    br
    strong> Etat :
    = status_tag( @booking_request.state)
    br
    - if @booking_request.contract_signed?
      strong> Contrat signé le :
      = time_tag @booking_request.contract_signed_at
      br
  .block
    .notification
      p = I18n.t("booking_request.states.#{@booking_request.state}.description")

  .block.buttons.is-justify-content-center
    - if @booking_request.unconfirmed?
      button.button.is-primary Renvoyer à nouveau
    - if @booking_request.signature_required?
      = link_to 'Signer le contrat', sign_booking_request_path(@booking_request), class: 'button is-primary', data: {turbo_method: :post}
    - if @booking_request.will_expire_soon?
      = link_to 'Renouveler mon contrat', renew_booking_request_path(@booking_request), class: 'button is-primary', data: {turbo_method: :post}
    a.button.is-outline(href=root_path) Revenir a accueil

app/views/booking_requests/_form.html.slim
= form_with(model: @booking_request, builder: BulmaFormBuilder::FormBuilder) do |form|
  = form.text_field :name, placeholder: 'Paul Dumont', help: 'Votre nom complet'
  = form.text_field :email, type: :email, placeholder: 'paul.dumont@example.com', help: 'Votre email'
  = form.text_field :phone, type: :phone, placeholder: '01 99 00 12 34', help: 'Un numero pour vous joindre'
  = form.text_area :biography, help: 'Votre projet en 5 mots minimum'
  div
    = form.submit 'Je réserve ma place', class: 'button is-primary'

app/views/booking_requests/new.html.slim
= render partial: 'form', booking_request: @booking_request, layout: 'components/card'

app/views/booking_requests/show.html.slim
== render partial: @booking_request, layout: 'components/card'

app/views/home/index.html.slim
.tile.is-ancestor
  .tile.is-parent.is-vertical
    .tile.is-child.notification.is-primary.is-light
      h2.title Boostez votre productivité
      p En choisissant de coworker, vous donnez un nouveau souffle à votre productivité. Vous êtes entouré de professionnels motivés, travaillant sur des projets passionnants, ce qui peut vous inspirer et vous donner de nouvelles idées.
    .tile.is-child.notification.is-info.is-light
      h2.title Espace de travail flexible
      p Notre espace de coworking est conçu pour s'adapter à vos besoins de travail en constante évolution. Que vous cherchiez un environnement calme pour vous concentrer sur votre travail personnel ou que vous ayez besoin d'un espace de réunion pour organiser une réunion en tête à tête.
  .tile.is-parent
    .tile.is-child.notification.is-success.is-light
      h2.title Réservez votre place maintenant
      p Ne manquez pas votre chance de devenir membre de notre communauté de coworking stimulante et performante. En réservant votre place dès maintenant, vous serez placé en tête de liste d'attente et sera assuré d'être parmi les premiers à bénéficier de notre espace de travail moderne et collaboratif.
      p.has-text-centered.mt-5
        a.button.is-primary.is-large(href=new_booking_request_path) Je réserve ma place

app/views/layouts/_header.html.slim
.nav.navbar.is-flex.is-justify-content-center.has-shadow.p-3.mb-5
  .navbar-brand
    a.navbar-item href=root_path
      =image_tag 'work-is-flex'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | App
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    = render partial: 'layouts/header'

    main.container
      = render partial: 'components/notice'
      = yield

    .footer.mt-4
      = link_to 'Admin', admin_booking_requests_path